### ISSUE TITLE
support for Litellm module and Azure , aws OCR modules 

### ISSUE THREAD

**Issue by saitej123** [Filimoa/open-parse#10]
please provide supprot for

support for Litellm module and Azure , aws OCR modules

**Comment by Filimoa** [comment]
Thanks for taking the time to leave a comment, unfortunately integrating proprietary OCR modules is beyond the scope of this library.  I don't think this would add much values on top of those solutions anyways.

**Comment by tan-yong-sheng** [comment]
Hi Filimoa,

I would like to suggest adding support for Litellm.

> Litellm is an open source project, which unifies the API call of 100+ LLMs (including Anthropic, Cohere, and Ollama, etc) in an OpenAI compatible format: https://github.com/BerriAI/litellm

I believe integrating Litellm would be a fantastic enhancement because people could choose to switch or use their preferred embedding model api instead of OpenAI's ones only when dealing with semantic processing. Thanks.
