### ISSUE TITLE
integration to llamaindex and langchain

### ISSUE THREAD

**Issue by saitej123** [Filimoa/open-parse#15]
can this service be part of data loaders or document index modules in llamaindex or langchain?

**Comment by Filimoa** [comment]
Yes it's pretty straightforward - I'll add a demo notebook soon.

**Comment by brianjking** [comment]
Great, thank you! +1 for LlamaIndex!

**Comment by Filimoa** [comment]
Added llama-index support with `v0.5.6`.  

If someone provides a langchain PR, I'll look into it but I think this library is much better used with llama-index.
