### ISSUE TITLE
NameError: name 'display' is not defined

### ISSUE THREAD

**Issue by Noexpert** [Filimoa/open-parse#3]
Firstly, thanks for this very promising project.
I tried experimenting to extract a table from a pdf.

When running the example code on my pdf I get the following error:
```
>>> for node in parsed_basic_doc.nodes:
...     display(node)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'display' is not defined
```

Is this wrong syntax, or perhaps some dependencies are missing?
Both pdfminer.six and PyMuPDF are installed.

Thanks

**Comment by Filimoa** [comment]
Sorry, that was meant to work inside a jupyter notebook! Correct code for regular python is. 

```
for node in parsed_basic_doc.nodes:
    print(node)
```

README has been updated!
