### ISSUE TITLE
Named temp directory never clears temp files

### ISSUE THREAD

**Issue by bradfox2** [Filimoa/open-parse#38]
### Initial Checks

- [X] I confirm that I'm on the latest version

### Description

Conversion to pymupdf via named temp files that are not deleted will run the disk out of space when on a long running job. 

see:
../open-parse/src/openparse/pdf.py:128

**Comment by Filimoa** [comment]
Thanks for opening this, I will look into this asap.

**Comment by bradfox2** [comment]
I didn't look through the code extensively - but creating the pymupdf object from bytestream works fine.  I can open PR if you'd like.

**Comment by Filimoa** [comment]
The tempfile was always hacky - thanks for pointing out you can create it from a bytestream. Should be fixed in v0.5.5.
