### ISSUE TITLE
Fix Documentation

### ISSUE THREAD

**Issue by moraneden** [Filimoa/open-parse#61]
### Initial Checks

- [X] I confirm that I'm on the latest version

### Description

the second param of the function export_with_bboxes is output_pdf and not output_path as in the docs.

```
pdf.export_with_bboxes(
    parsed_basic_doc.nodes,
    output_path="./sample-docs/mobile-home-manual-marked-up.pdf"
)
```

should be:

```
        return pdf_file.export_with_bboxes(
            parsed_basic_doc.nodes,
            output_pdf="./sample-docs/mobile-home-manual-marked-up.pdf"
        )
```

https://github.com/Filimoa/open-parse/blob/main/docs/visualization.md

### Example Code

```Python
return pdf_file.export_with_bboxes(
            parsed_basic_doc.nodes,
            output_pdf="./sample-docs/mobile-home-manual-marked-up.pdf"
        )
```

### Python, open-parse & OS Version

```Text
N/A
```

**Comment by Filimoa** [comment]
Thanks for the PR!
