### ISSUE TITLE
BadRequestError: Error code: 400

### ISSUE THREAD

**Issue by NuiMrme** [Filimoa/open-parse#72]
### Initial Checks

- [X] I confirm that I'm on the latest version

### Description

    ``` semantic_pipeline = processing.SemanticIngestionPipeline(
    openai_api_key=openai_api_key,
    model="text-embedding-3-large",
    min_tokens=2,
    max_tokens=4000,  
    )
    parser = DocumentParser(
        processing_pipeline=semantic_pipeline,
        table_args={"parsing_algorithm": "pymupdf",
        "table_output_format": "markdown",
                    }
    )
   
 this is basically almost the same as the one in the examples , it comes back with an an openai error : 
    BadRequestError: Error code: 400 - {'error': {'message': "'$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.", 'type': 'invalid_request_error', 'param': None, 'code': None}}

### Example Code

_No response_

### Python, open-parse & OS Version

```Text
python_version: 3.12.3
             operating_system: Linux
                   os_version: 6.8.0-45-generic
           open-parse version: 0.6.0
                 install path: /home/develop/Desktop/RAG_BSS/.bss_iln_venv/lib/python3.12/site-packages/openparse
               python version: 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
                     platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.39
             related packages: torchvision-0.19.1 tokenizers-0.20.0 PyMuPDF-1.24.11 pydantic-2.9.2 torch-2.4.1 transformers-4.45.2
```

**Comment by NuiMrme** [comment]
I think it is even more than empty strings , I remember passing by this sanitization but it didn't solve the isse. My text contains a whole lot of different symbols and stuff. So I solved the problem basically getting rid of the batching mechanism which sometimes the cutt-off will result in a bad string. To be honest I don't know the purpose of batching on this , if we have our chunk already. If it serves nothing and causes problems maybe it should be considered for deletion ?

**Comment by Filimoa** [comment]
That's strange - should not be happening because we have a step that filters out Nodes with less than 50 tokens called RemoveNodesBelowNTokens.  Does someone have a sample pdf?

**Comment by NuiMrme** [comment]
As I mentioned earlier I don't think it is about empty strings, but about bad strings when the batching cut the string at a position with a special symbol or something, removing the batches solved the issue completely. Question is why we need batches to begin with ?

**Comment by Filimoa** [comment]
Without batching you'll end up with a bunch of small, fragmented nodes. So a heading will be separated from the paragraph, bulleted lists will be split apart, etc.

With that said you can disabled all transforms by passing an empty pipeline

``` py
parser = openparse.DocumentParser(processing_pipeline=None)
```

**Comment by NuiMrme** [comment]
I'm talking about this batching here, the fixed size 256 batch, it doesn't help the case and bulleted lists will be divided too

`def embed_many(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for a list of texts in batches.

        Args:
            texts (list[str]): The list of texts to embed.
            batch_size (int): The number of texts to process in each batch.

        Returns:
            List[List[float]]: A list of embeddings.
        """
        res = []
        for i in range(0, len(texts), self.batch_size):
            batch_texts = texts[i : i + self.batch_size]
            api_resp = self.client.embeddings.create(
                input=batch_texts, model=self.model
            )
            batch_res = [val.embedding for val in api_resp.data]
            res.extend(batch_res)

        return res`

**Comment by NuiMrme** [comment]
Same error with langchain on `parsed_document = parser.parse(file_path, ocr=True)` . 
This is an OpenParse problem. Thing is, it worked at first then all of a sudden the error is reproduced.

**Comment by Filimoa** [comment]
Sorry for how long this took but it's fixed in `0.7.0`

**Comment by NuiMrme** [comment]
what was the problem and how did you fix it ?

**Comment by Filimoa** [comment]
ImageNodes that only contain Image Elements inherently don't have any text attached to them. These were getting passed to the semantic pipeline and crashing OpenAI. Now Image elements get grouped with all the text on a page.
